# Generated by Django 5.2.4 on 2025-07-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
    ]
