# Generated by Django 5.2.4 on 2025-07-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(max_length=150, null=True, verbose_name="Статус платежа"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True, help_text="Ссылка на оплату", max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
