# Generated by Django 5.2.4 on 2025-07-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_status_alter_payment_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
    ]
