# Generated by Django 5.2.4 on 2025-07-20 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата оплаты"),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет")],
                default="transfer",
                help_text="Выберите способ оплаты",
                max_length=50,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("pending", "Ожидает оплаты"), ("paid", "Оплачено"), ("canceled", "Отменено")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
