# Generated by Django 5.2.4 on 2025-07-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_payment_payment_date_payment_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_currency",
            field=models.CharField(default="rub", max_length=3),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_customer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
