# Generated by Django 5.2.4 on 2025-07-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_payment_stripe_amount_payment_stripe_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_amount",
            field=models.IntegerField(blank=True, null=True, verbose_name="Сумма в копейках"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_customer_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email пользователя из 'Stripe'"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_status",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Статус Stripe"),
        ),
    ]
