# Generated by Django 5.2.4 on 2025-07-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_payment_stripe_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="stripe_customer_email",
            new_name="customer_email",
        ),
    ]
