# Generated by Django 5.2.4 on 2025-07-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_payments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={
                "ordering": ["payment_date", "amount"],
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
        migrations.RenameField(
            model_name="course",
            old_name="title",
            new_name="course_title",
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[("Наличные", "Наличные"), ("Перевод на счет", "Перевод на счет")],
                default="Перевод на счет",
                help_text="Выберите способ оплаты",
                max_length=50,
                verbose_name="способ оплаты",
            ),
        ),
    ]
