# Generated by Django 5.2.4 on 2025-07-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="updated_at",
        ),
    ]
