# Generated by Django 5.2.4 on 2025-07-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_remove_subscription_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["id"], "verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["id"], "verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
    ]
