# Generated by Django 5.2.4 on 2025-07-14 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0009_alter_payments_options_alter_course_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                default=1,
                help_text="Курс по подписке",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_subscriptions",
                to="materials.course",
            ),
            preserve_default=False,
        ),
    ]
