# Generated by Django 5.2.4 on 2025-07-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0010_alter_subscription_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Укажите стоимость курса",
                max_digits=20,
                null=True,
                verbose_name="Стоимость курса",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Укажите стоимость урока",
                max_digits=20,
                null=True,
                verbose_name="Стоимость урока",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_title",
            field=models.CharField(help_text="Укажите название курса", max_length=200, verbose_name="Название курса"),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, help_text="Введите описание курса", null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="materials/preview",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, help_text="Введите описание урока", null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Добавьте ссылку на видео",
                max_length=500,
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="materials/preview",
                verbose_name="Превью(картинка)",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Укажите сумму оплаты",
                max_digits=20,
                null=True,
                verbose_name="Сумма оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateTimeField(
                blank=True, help_text="Укажите дату оплаты", null=True, verbose_name="Дата оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[("Наличные", "Наличные"), ("Перевод на счет", "Перевод на счет")],
                default="Перевод на счет",
                help_text="Выберите способ оплаты",
                max_length=50,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
