# Generated by Django 5.2.4 on 2025-07-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0011_course_price_lesson_price_alter_course_course_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Укажите стоимость курса",
                max_digits=20,
                null=True,
                verbose_name="Стоимость курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Укажите стоимость урока",
                max_digits=20,
                null=True,
                verbose_name="Стоимость урока",
            ),
        ),
    ]
