# Generated by Django 5.2.4 on 2025-07-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0012_alter_course_price_alter_lesson_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=15000.0,
                help_text="Укажите стоимость курса",
                max_digits=20,
                verbose_name="Стоимость курса",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Укажите стоимость урока",
                max_digits=20,
                verbose_name="Стоимость урока",
            ),
            preserve_default=False,
        ),
    ]
