# Generated by Django 5.2.4 on 2025-07-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0014_course_created_at_course_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания курса"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания урока"),
        ),
    ]
