# Generated by Django 5.2.4 on 2025-07-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0015_alter_course_created_at_alter_lesson_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payments",
        ),
    ]
